# Configuration file for ubuntu_setup.sh
# Uncomment each line after configuration.
# Both parameters are required to authenticate and join the computer to a domain.

# Configure domain name
# domain=EXAMPLE.COM

# Configure domain controller
# dc=dc.example.com
